/**
 * Turns the shirt faces in assets/fonts into a TypeScript module.
 *
 * Same reason as `lib/poster/font-data.ts`: Next traces imports, so a font read
 * from assets/ with readFile() simply is not there in production. A module
 * constant always is.
 *
 * Run: node node_modules/.bin/tsx --tsconfig scripts/tsconfig.json \
 *        scripts/embed-fonts.ts
 */
import { promises as fs } from "fs";
import path from "path";

const FACES: { key: string; file: string; name: string }[] = [
  { key: "OSWALD", file: "oswald.ttf", name: "Oswald Bold" },
  { key: "RUSSO", file: "russo-one.ttf", name: "Russo One" },
  { key: "PATTAYA", file: "pattaya.ttf", name: "Pattaya" },
  { key: "PLAYFAIR", file: "playfair-display.ttf", name: "Playfair Display ExtraBold" },
  { key: "NUNITO", file: "nunito.ttf", name: "Nunito ExtraBold" },
  { key: "MANROPE", file: "manrope.ttf", name: "Manrope Bold" },
];

async function main() {
  const dir = path.join(process.cwd(), "assets", "fonts");
  const parts = [
    "/**",
    " * The shirt faces, embedded as base64.",
    " *",
    " * Generated by scripts/embed-fonts.ts — do not edit by hand.",
    " *",
    " * Embedded rather than read from disk for the same reason as",
    " * lib/poster/font-data.ts: Next.js bundles only traced imports, so a font",
    " * loaded with readFile() from assets/ is missing in production. As module",
    " * constants they are always in the bundle.",
    " *",
    " * All six are SIL Open Font License 1.1 and carry Cyrillic.",
    " */",
    "",
  ];
  for (const f of FACES) {
    const b64 = (await fs.readFile(path.join(dir, f.file))).toString("base64");
    parts.push(`/** ${f.name} */`);
    parts.push(`export const ${f.key}_B64 =`);
    parts.push(`  "${b64}";`);
    parts.push("");
    console.log(`${f.key.padEnd(10)} ${(b64.length / 1024).toFixed(0)} KB`);
  }
  await fs.writeFile(
    path.join(process.cwd(), "src", "lib", "print", "font-data.ts"),
    parts.join("\n")
  );
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
